//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementDetail
    {
        public int DisbursementDetailID { get; set; }
        public int DisbursementID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> TempQty { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Disbursement Disbursement { get; set; }
    }
}
