//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterimRetrievalStockTable
    {
        public int InterimRetrievalStockTableID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> WaitingQty { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
    }
}
