//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionDetail
    {
        public int RequisitionDetailID { get; set; }
        public Nullable<int> RequisitionID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<int> OutstandingQty { get; set; }
        public Nullable<int> DisbursedQty { get; set; }
        public Nullable<int> DisbursementID { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Disbursement Disbursement { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
