//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetrievalDetail
    {
        public int RetrievalDetailID { get; set; }
        public int RetrievalID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> QtyNeeded { get; set; }
        public Nullable<int> ActualQty { get; set; }
        public string Status { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
        public virtual Retrieval Retrieval { get; set; }
    }
}
