//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1LUSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCard
    {
        public int TransactionID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Dept_Supplier_Adjt { get; set; }
        public Nullable<int> Qty { get; set; }
        public string AddorMinus { get; set; }
        public Nullable<int> Balance { get; set; }
    
        public virtual Catalogue Catalogue { get; set; }
    }
}
